version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: es8
    restart: always
    environment:
      - node.name=es8-node-1
      - cluster.name=es8-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # 强制禁用安全插件
    command: >
      bash -c "
      echo 'xpack.security.enabled: false' >> /usr/share/elasticsearch/config/elasticsearch.yml;
      /usr/local/bin/docker-entrypoint.sh eswrapper
      "
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/Develop/7_Opt/elasticsearch/data:/usr/share/elasticsearch/data
      - ~/Develop/7_Opt/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-network

networks:
  es-network:
    driver: bridge